### ISSUE TITLE
getting "Failed to determine dependencies" with nx11 

### ISSUE THREAD

**Issue by cakeinpanic** [jscutlery/semver#443]
Hi, I'm getting `Failed to determine dependencies.` error when running `nx run-many --target=version --with-deps` 

I debugged into your code and found out that this method throws an error `TypeError: (0 , project_graph_1.createProjectGraphAsync) is not a function`

```
function getProjectDependencies(projectName) {
    return (0, tslib_1.__awaiter)(this, void 0, void 0, function* () {
        // The shape of the project graph can still change. So we're pinning the
        // version of the graph to 5.0.
        const dependencyGraph = yield (0, project_graph_1.createProjectGraphAsync)('5.0');
        return getProjectsFromDependencies(dependencyGraph.dependencies[projectName]);
    });
}
```

I assume that the package is incompatible with nx 11 which I am using
Tell me please which version of your package is compatible with nx 11 (cause I can't upgrade it)?

My package.json currently:
```
"@nrwl/workspace": "11.6.3",
"@jscutlery/semver": "2.18.1",
```

**Comment by edbzn** [comment]
Hi @cakeinpanic, are you using the `--trackDeps` option with semver? I'm working on a fix to support Nx 11.

**Comment by cakeinpanic** [comment]
Hi, thank you for fast response!
yes, I have `trackDeps` in my `workspace.json`

**Comment by edbzn** [comment]
@cakeinpanic this has been fixed in [2.18.2](https://github.com/jscutlery/semver/commit/19b3e56b933b62024f6d5eb6dd9ad55592c5a781), thanks for reporting this.

**Comment by cakeinpanic** [comment]
thank you, @edbzn, works like a charm!

**Comment by mangersmiovision** [comment]
This is broken again as of 2.21.1. It works well in 2.21.0.

**Comment by cakeinpanic** [comment]
Still broken in. 2.23.3

I also noticed that it installs nx14 as a dependency. I assume it may cause this problem. Isn't it better to have nx as a _peerDependency_?

**Comment by edbzn** [comment]
@cakeinpanic @nrwl/devkit is already a peer dependency 🤔

**Comment by edbzn** [comment]
@cakeinpanic did you try the latest 2.23.4?

**Comment by matheo** [comment]
@edbzn it's happening with the latest `2.27.1` :(
https://github.com/myndpm/open-source/actions/runs/3155398016/jobs/5134049221#step:6:27
